name: OpenCode
on:
  workflow_dispatch:
    inputs:
      prompt:
        description: Prompt for OpenCode
        required: true
        default: Analyze the repository and suggest improvements
  issue_comment:
    types: [created]

jobs:
  opencode:
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'issue_comment' &&
        (contains(github.event.comment.body, '/oc') ||
         contains(github.event.comment.body, '/opencode')))
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - uses: anomalyco/opencode/github@latest
        env:
          OPENCODE_API_KEY: ${{ secrets.OPENCODE_API_KEY }}
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
        with:
          model: opencode/deepseek-v4-flash-free
          prompt: ${{ inputs.prompt }}
